[2025-05-02T22:10:40.330+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T22:10:40.351+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_etl_then_elt.trigger_etl_dag scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:10:40.363+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_etl_then_elt.trigger_etl_dag scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T22:10:40.363+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-02T22:10:40.374+0000] {taskinstance.py:2888} INFO - Executing <Task(TriggerDagRunOperator): trigger_etl_dag> on 2025-05-01 00:00:00+00:00
[2025-05-02T22:10:40.383+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'trigger_etl_then_elt', 'trigger_etl_dag', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Etl_elt_trigger.py', '--cfg-path', '/tmp/tmpiz2iy4ka']
[2025-05-02T22:10:40.386+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask trigger_etl_dag
[2025-05-02T22:10:40.387+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=923) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-02T22:10:40.387+0000] {standard_task_runner.py:72} INFO - Started process 925 to run task
[2025-05-02T22:10:40.442+0000] {task_command.py:467} INFO - Running <TaskInstance: trigger_etl_then_elt.trigger_etl_dag scheduled__2025-05-01T00:00:00+00:00 [running]> on host edac5e2fb0a3
[2025-05-02T22:10:40.522+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_etl_then_elt' AIRFLOW_CTX_TASK_ID='trigger_etl_dag' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T22:10:40.523+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-02T22:10:40.605+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:11:40.675+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:12:40.722+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:13:40.762+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:14:40.788+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:15:40.843+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:16:40.900+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:17:40.941+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:18:40.978+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:19:41.019+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:20:41.070+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:21:41.117+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:22:41.146+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:23:41.182+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:24:41.202+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:25:41.237+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:26:41.271+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:27:41.307+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:28:41.333+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:29:41.359+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:30:41.395+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:31:41.432+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:37:16.689+0000] {job.py:229} INFO - Heartbeat recovered after 303.13 seconds
[2025-05-02T22:37:39.615+0000] {trigger_dagrun.py:257} INFO - Waiting for tesla_stock_sentiment_api_etl on 2025-05-02 22:10:40.543053+00:00 to become allowed state ['success'] ...
[2025-05-02T22:43:15.200+0000] {job.py:229} INFO - Heartbeat recovered after 302.79 seconds
[2025-05-02T22:43:37.422+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tesla_stock_sentiment_api_etl failed with failed states failed
[2025-05-02T22:43:37.438+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=trigger_etl_then_elt, task_id=trigger_etl_dag, run_id=scheduled__2025-05-01T00:00:00+00:00, execution_date=20250501T000000, start_date=20250502T221040, end_date=20250502T224337
[2025-05-02T22:43:37.461+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-02T22:43:37.463+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task trigger_etl_dag (tesla_stock_sentiment_api_etl failed with failed states failed; 925)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/trigger_dagrun.py", line 269, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: tesla_stock_sentiment_api_etl failed with failed states failed
[2025-05-02T22:43:37.502+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-02T22:43:37.556+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T22:43:37.561+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
